import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import AXIOSInit from "../components/providers/AXIOSInit";
import { Suspense, type ReactNode } from "react";
import InitProvider from "../components/providers/InitProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Suspense>
          <AntdRegistry>
            <InitProvider>
              <AXIOSInit>
                {children}
              </AXIOSInit>
            </InitProvider>
          </AntdRegistry>
        </Suspense>
      </body>
    </html>
  );
}
